-- 코드를 작성해주세요

 
SELECT A.ITEM_ID,ITEM_NAME,RARITY FROM ITEM_INFO AS A JOIN ITEM_TREE AS B ON A.ITEM_ID = B.ITEM_ID WHERE A.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_INFO AS A JOIN ITEM_TREE AS B ON A.ITEM_ID = B.ITEM_ID WHERE PARENT_ITEM_ID IS NOT NULL ) ORDER BY A.ITEM_ID DESC;