-- 코드를 입력하세요
SELECT 
CAR.CAR_ID,
CAR.CAR_TYPE,
ROUND(CAR.DAILY_FEE * 30 * (100-DISCOUNT.DISCOUNT_RATE)*0.01)  AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR 
JOIN
CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DISCOUNT 
ON CAR.CAR_TYPE = DISCOUNT.CAR_TYPE
AND DISCOUNT.DURATION_TYPE = '30일 이상'
LEFT JOIN
CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY 
ON CAR.CAR_ID = HISTORY.CAR_ID 

AND (HISTORY.START_DATE <='2022-11-30' AND HISTORY.END_DATE >='2022-11-01')
WHERE 
CAR.CAR_TYPE IN ('세단' ,'SUV') 
AND HISTORY.CAR_ID IS NULL
AND  ROUND(CAR.DAILY_FEE * 30 * (100-DISCOUNT.DISCOUNT_RATE)*0.01) BETWEEN 500000 AND 2000000-1
ORDER BY FEE DESC,CAR.CAR_TYPE,CAR.CAR_ID DESC;