-- 코드를 작성해주세요


SELECT 
  CONCAT(QQ.QUARTER, 'Q') AS QUARTER,
  COUNT(*) AS ECOLI_COUNT
FROM (
  SELECT 
    QUARTER(DIFFERENTIATION_DATE) AS QUARTER
  FROM ECOLI_DATA
) AS QQ
GROUP BY QQ.QUARTER
ORDER BY QQ.QUARTER;