-- 코드를 작성해주세요

   (SELECT CONCAT(1,'Q') AS QUARTER ,COUNT(ID) AS ECOLI_COUNT FROM ECOLI_DATA WHERE MONTH(DIFFERENTIATION_DATE) <=3) 
             UNION
        (SELECT CONCAT(2,'Q'),COUNT(ID) AS ECOLI_COUNT  FROM ECOLI_DATA WHERE MONTH(DIFFERENTIATION_DATE)  BETWEEN 4 AND 6) 
                         UNION
                      (SELECT CONCAT(3,'Q'),COUNT(ID) AS ECOLI_COUNT FROM ECOLI_DATA WHERE MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9) 
                         UNION
                      (SELECT CONCAT(4,'Q'),COUNT(ID) AS ECOLI_COUNT FROM ECOLI_DATA WHERE MONTH(DIFFERENTIATION_DATE) BETWEEN 10 AND 12) 
                      
             
             
   
    
              
             