SELECT HISTORY_ID ,
ROUND(C.DAILY_FEE * (DATEDIFF(END_DATE,START_DATE)+1) *
CASE 
WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90
THEN (SELECT (100-DISCOUNT_RATE) *0.01 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = C.CAR_TYPE AND DURATION_TYPE ='90일 이상')
WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 30
THEN (SELECT (100-DISCOUNT_RATE) *0.01 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = C.CAR_TYPE AND DURATION_TYPE ='30일 이상')
WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 7
THEN (SELECT (100-DISCOUNT_RATE) *0.01 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = C.CAR_TYPE AND DURATION_TYPE ='7일 이상')
ELSE 1
END,0)
AS FEE 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
LEFT JOIN CAR_RENTAL_COMPANY_CAR AS C ON H.CAR_ID = C.CAR_ID
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;
;