-- 코드를 입력하세요
SELECT  FIRST_HALF.FLAVOR FROM FIRST_HALF JOIN (SELECT FLAVOR,SUM(TOTAL_ORDER) AS TOTAL FROM JULY GROUP BY FLAVOR) AS A ON FIRST_HALF.FLAVOR = A.FLAVOR
ORDER BY A.TOTAL+FIRST_HALF.TOTAL_ORDER DESC LIMIT 3;