-- 코드를 입력하세요
WITH RECURSIVE H AS (
    SELECT 0 AS HOUR
    UNION ALL
    
    SELECT HOUR+1 FROM H
    WHERE HOUR <23
)
SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT FROM H LEFT OUTER JOIN ANIMAL_OUTS AS A ON H.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR ORDER BY HOUR;