-- 코드를 작성해주세요
SELECT 
year(A.DIFFERENTIATION_DATE) AS YEAR,
(B.MAX_SIZE-SIZE_OF_COLONY) AS YEAR_DEV,
A.ID 
FROM ECOLI_DATA AS A JOIN 
(SELECT year(DIFFERENTIATION_DATE) AS YEAR,MAX(SIZE_OF_COLONY) AS MAX_SIZE FROM ECOLI_DATA GROUP BY year(DIFFERENTIATION_DATE)) AS B 
ON year(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV;