-- 코드를 작성해주세요
SELECT SCORE,EMP_NO,EMP_NAME,POSITION,EMAIL FROM
(SELECT SUM(SCORE) AS SCORE ,G.EMP_NO,EMP_NAME,POSITION,EMAIL FROM HR_EMPLOYEES AS E JOIN HR_GRADE AS G ON E.EMP_NO = G.EMP_NO GROUP BY G.EMP_NO) AS  A ORDER BY SCORE DESC LIMIT 1;