-- 코드를 작성해주세요
SELECT COUNT(A.ID) AS FISH_COUNT, MAX(FISH_INFO.LENGTH) AS MAX_LENGTH,A.FISH_TYPE 
FROM FISH_INFO JOIN (SELECT ID, IF(LENGTH<=10, 10, LENGTH) AS LENGTH, FISH_TYPE FROM FISH_INFO ) AS A ON FISH_INFO.ID = A.ID
GROUP BY A.FISH_TYPE HAVING AVG(A.LENGTH) >=33
ORDER BY A.FISH_TYPE;