-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT, MAX(A.LENGTH) AS MAX_LENGTH,A.FISH_TYPE 
FROM  (SELECT IF(LENGTH<=10, 10, LENGTH) AS LENGTH, FISH_TYPE FROM FISH_INFO ) AS A
GROUP BY A.FISH_TYPE HAVING AVG(A.LENGTH) >=33
ORDER BY A.FISH_TYPE;