WITH 
PYTHON_CODE AS (
  SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE NAME = 'Python'
),
CSHARP_CODE AS (
  SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE NAME = 'C#'
),
FRONTEND_CODE AS (
  SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE CATEGORY = 'Front End'
)

SELECT
  CASE
    WHEN D.SKILL_CODE & (SELECT CODE FROM PYTHON_CODE) > 0
         AND D.SKILL_CODE & (SELECT CODE FROM FRONTEND_CODE) > 0 THEN 'A'
    WHEN D.SKILL_CODE & (SELECT CODE FROM CSHARP_CODE) > 0 THEN 'B'
    WHEN D.SKILL_CODE & (SELECT CODE FROM FRONTEND_CODE) > 0 THEN 'C'
    ELSE NULL
  END AS GRADE,
  D.ID,
  D.EMAIL
FROM DEVELOPERS D
WHERE 
  (D.SKILL_CODE & (SELECT CODE FROM PYTHON_CODE) > 0 AND D.SKILL_CODE & (SELECT CODE FROM FRONTEND_CODE) > 0)
  OR (D.SKILL_CODE & (SELECT CODE FROM CSHARP_CODE) > 0)
  OR (D.SKILL_CODE & (SELECT CODE FROM FRONTEND_CODE) > 0)
ORDER BY GRADE,D.ID;