-- 코드를 작성해주세요
WITH A AS(
SELECT ID FROM DEVELOPERS WHERE 
   SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0
AND
SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') > 0
)

,B AS(
SELECT ID FROM DEVELOPERS WHERE 
    SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME= 'C#')  > 0
)

, C AS(
SELECT ID FROM DEVELOPERS WHERE 
    SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') >0
)

SELECT IF(A.ID IS NOT NULL,'A',IF(B.ID IS NOT NULL, 'B','C')) AS GRADE,D.ID,EMAIL FROM DEVELOPERS AS D LEFT JOIN A ON D.ID = A.ID LEFT JOIN B ON D.ID = B.ID LEFT JOIN C ON D.ID = C.ID
WHERE A.ID IS NOT NULL OR B.ID IS NOT NULL OR C.ID IS NOT NULL
ORDER BY GRADE,ID