WITH RECURSIVE G AS(
    SELECT (MIN(PRICE) - MIN(PRICE)%10000) AS PRICE_GROUP
    FROM PRODUCT
    
    UNION ALL
    
    SELECT PRICE_GROUP+10000 FROM G
    WHERE PRICE_GROUP < (SELECT MAX(PRICE) FROM PRODUCT)
)
SELECT PRICE_GROUP,COUNT(PRODUCT_ID) AS PRODUCTS FROM PRODUCT,G WHERE FLOOR(PRICE / 10000) = FLOOR(PRICE_GROUP / 10000) 
GROUP BY PRICE_GROUP 
ORDER BY PRICE_GROUP;